[package]
name = "exotic"
version = "0.2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
paste = "1.0.7"
rand = "0.8.5"
slas = { git = "https://github.com/unic0rn9k/slas", default-features = false, features = ["blas"] }
